services:
    maindevcontainer:
        image: "${DEVCONTAINER_IMAGE_NAME:-bash:5}"
        env_file:
            - .env
        volumes:
            - workdir:/workdir
            - home:/home
        tmpfs: /tmp:exec,mode=1777
        tty: true
        stdin_open: true
        command: ["sleep", "infinity"]
        deploy:
            resources:
                reservations:
                    memory: "${RESOURCES_RAM:-2G}"
                limits:
                    memory: "${RESOURCES_RAM:-2G}"

volumes:
    home:
    workdir:
